sonar.organization=ahmed6394
sonar.projectKey=ahmed6394_devops-incedent-app
sonar.projectName=DevOps Incident Management
sonar.host.url=https://sonarcloud.io
sonar.sources=backend/src,frontend/src
sonar.sourceEncoding=UTF-8
sonar.exclusions=frontend/dist/**,**/node_modules/**
